### ISSUE TITLE
How does the library handle breaking changes(examples provided)?

### ISSUE THREAD

**Issue by DavidTheExplorer** [Exlll/ConfigLib#20]
Hello, the library looks awesome and I want to start using it, but I do have an important question...
Imagine a plugin whose version is 1, and it created the following config:
```yml
Settings:
    # How much money is given to every player on the winner team
    Reward: 100
```
Everything is working well.\
After some time I want to release version 2 which not only rewards the top 3 players, but also each one gets a different amount of money:
```yml
Settings:
    # The rewards in decreasing order(first place gets the first amount, second place the second, etc)
    Rewards:
        - 100
        - 70
        - 50
```
Notice that:
-  _Reward_ was renamed to _Rewards_
- _Rewards_ is now a list instead of a field

My question is how does the library handle this breaking change? 
What if the user doesn't specify a number to neither configs - does the library throw a descriptive error message, returns a default value, or ignores the setting(if it's within a list)?\
\
 I'm asking these questions because my plugin is exactly in this situation and without clear answers I can't use your library... Thank you!
